{-# OPTIONS_GHC -Wno-orphans #-}
-- singletons emits defunctionalization symbols (FooSym0) we don't use.
{-# OPTIONS_GHC -Wno-unused-top-binds #-}

module Servant.Auth.RolesSpec (spec) where

import Servant.Auth.Roles.TH
import Servant.Auth.RolesErrorFixture (underivedDecidable)
import Control.Exception (SomeException, evaluate, try)
import Control.Monad.Except (throwError)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.IORef (IORef, modifyIORef', newIORef, readIORef)
import Network.HTTP.Types (Header, HeaderName, hAccept)
import Network.Wai (Application, Request, requestHeaders)
import Network.Wai.Test (SResponse)
import Servant.API (Get, JSON, type (:<|>) (..), type (:>))
import Servant.API.Experimental.Auth (AuthProtect)
import Servant.Server (Context (..), Handler, Server, err401, serveWithContext)
import Servant.Server.Experimental.Auth (AuthHandler, AuthServerData, mkAuthHandler)
import Test.Hspec (Spec, describe, expectationFailure, it, shouldContain, shouldReturn)
import Test.Hspec.Wai (WaiSession, get, matchStatus, request, shouldRespondWith, with)
import Test.Hspec.Wai.Internal (runWaiSession)

--------------------------------------------------------------------------------
-- Scheme 1: role-indexed auth

data UserRole = Viewer | Editor | Admin

$(deriveOrdRole ''UserRole)

newtype RoleAuth (r :: UserRole) = RoleAuth {rName :: String}

type instance AuthServerData (AuthProtect "role-auth") = SomeRole RoleAuth

parseRole :: Request -> Maybe (SomeRole RoleAuth)
parseRole req = case lookup "X-Role" (requestHeaders req) of
  Just "viewer" -> Just (someUserRole Viewer (RoleAuth "Reed"))
  Just "editor" -> Just (someUserRole Editor (RoleAuth "Lyxia"))
  Just "admin" -> Just (someUserRole Admin (RoleAuth "Sandy"))
  _ -> Nothing

roleAuthHandler :: AuthHandler Request (SomeRole RoleAuth)
roleAuthHandler = mkAuthHandler $ maybe (throwError err401) pure . parseRole

-- | Statically admin-gated subroutine. The proof comes from Satisfies.
-- IsAtleastAdmin is generated by deriveOrdRole (one alias per constructor).
banUser :: (IsAtleastAdmin userAuth) => RoleAuth userAuth -> String
banUser auth = "banned by " <> rName auth

--------------------------------------------------------------------------------
-- Test API (separate paths)

type RoleViewerAPI = RequireRole "role-auth" 'Viewer :> "viewer" :> Get '[JSON] String

type RoleEditorAPI = RequireRole "role-auth" 'Editor :> "editor" :> Get '[JSON] String

type RoleAdminAPI = RequireRole "role-auth" 'Admin :> "admin" :> Get '[JSON] String

type RoleAPI = RoleViewerAPI :<|> RoleEditorAPI :<|> RoleAdminAPI

roleServer :: Server RoleAPI
roleServer = viewerH :<|> editorH :<|> adminH
  where
    viewerH :: Satisfies 'Viewer RoleAuth -> Handler String
    viewerH (Satisfies _ auth) = pure ("viewer: " <> rName auth)

    editorH :: Satisfies 'Editor RoleAuth -> Handler String
    editorH (Satisfies _ auth) = pure ("editor: " <> rName auth)

    adminH :: Satisfies 'Admin RoleAuth -> Handler String
    adminH (Satisfies UserRoleProof auth) = pure (banUser auth) -- proof flows into banUser

roleApp :: IO Application
roleApp = pure $ serveWithContext (Proxy @RoleAPI) (roleAuthHandler :. EmptyContext) roleServer

--------------------------------------------------------------------------------
-- Test API (same path, role-based fallthrough)
--
-- Routes ordered most-restrictive-first:
--   Admin  -> "admin panel"
--   Editor -> "editor panel"
--   Viewer -> "viewer panel"

type PanelAdminAPI = RequireRole "role-auth" 'Admin :> "panel" :> Get '[JSON] String

type PanelEditorAPI = RequireRole "role-auth" 'Editor :> "panel" :> Get '[JSON] String

type PanelViewerAPI = RequireRole "role-auth" 'Viewer :> "panel" :> Get '[JSON] String

type FallthroughAPI = PanelAdminAPI :<|> PanelEditorAPI :<|> PanelViewerAPI

fallthroughServer :: Server FallthroughAPI
fallthroughServer = pAdmin :<|> pEditor :<|> pViewer
  where
    pAdmin :: Satisfies 'Admin RoleAuth -> Handler String
    pAdmin _ = pure "admin panel"

    pEditor :: Satisfies 'Editor RoleAuth -> Handler String
    pEditor _ = pure "editor panel"

    pViewer :: Satisfies 'Viewer RoleAuth -> Handler String
    pViewer _ = pure "viewer panel"

fallthroughApp :: IO Application
fallthroughApp = pure $ serveWithContext (Proxy @FallthroughAPI) (roleAuthHandler :. EmptyContext) fallthroughServer

--------------------------------------------------------------------------------
-- Test API (auth invocation counting)

countingRoleHandler :: IORef Int -> AuthHandler Request (SomeRole RoleAuth)
countingRoleHandler counter = mkAuthHandler $ \req -> do
  liftIO $ modifyIORef' counter (+ 1)
  maybe (throwError err401) pure (parseRole req)

countingApp :: IORef Int -> IO Application
countingApp counter =
  pure $ serveWithContext (Proxy @FallthroughAPI) (countingRoleHandler counter :. EmptyContext) fallthroughServer

--------------------------------------------------------------------------------
-- Test API (public route behind role gates)
--
-- Regression guard. A trailing unauthenticated route is unreachable when it
-- sits behind RequireRole alternatives on the same path. Because authentication
-- failure is fatal, an unauthenticated request short-circuits at the first
-- RequireRole (401) and never falls through to the public route. That route is
-- dead code here. Only an authenticated user whose role is below every gate
-- could reach it, and no such role exists in UserRole.

type PanelPublicAPI = "panel" :> Get '[JSON] String

type AnonAPI = FallthroughAPI :<|> PanelPublicAPI

anonServer :: Server AnonAPI
anonServer = fallthroughServer :<|> pure "public panel"

anonApp :: IO Application
anonApp = pure $ serveWithContext (Proxy @AnonAPI) (roleAuthHandler :. EmptyContext) anonServer

--------------------------------------------------------------------------------
-- Scheme 2: flat, non-hierarchical roles (exact match)

data Region = US | EU | APAC

$(deriveEqRole ''Region)

newtype RegionAuth (r :: Region) = RegionAuth {rTenant :: String}

type instance AuthServerData (AuthProtect "region-auth") = SomeRole RegionAuth

parseRegion :: Request -> Maybe (SomeRole RegionAuth)
parseRegion req = case lookup "X-Region" (requestHeaders req) of
  Just "us" -> Just (someRegion US (RegionAuth "acme-us"))
  Just "eu" -> Just (someRegion EU (RegionAuth "acme-eu"))
  Just "apac" -> Just (someRegion APAC (RegionAuth "acme-apac"))
  _ -> Nothing

regionAuthHandler :: AuthHandler Request (SomeRole RegionAuth)
regionAuthHandler = mkAuthHandler $ maybe (throwError err401) pure . parseRegion

-- | EU-only operation. The proof that r ~ 'EU comes from Satisfies, no re-check.
-- IsEU is generated by deriveEqRole (one alias per constructor).
--
-- NOTE: this could be @RegionAuth 'EU@ but we provide @Is<Role>@ aliases for
-- consistency.
gdprExport :: (IsEU r) => RegionAuth r -> String
gdprExport auth = "GDPR export for " <> rTenant auth

type USAPI = RequireRole "region-auth" 'US :> "us" :> Get '[JSON] String

type EUAPI = RequireRole "region-auth" 'EU :> "eu" :> Get '[JSON] String

type APACAPI = RequireRole "region-auth" 'APAC :> "apac" :> Get '[JSON] String

type RegionAPI = USAPI :<|> EUAPI :<|> APACAPI

regionServer :: Server RegionAPI
regionServer = usH :<|> euH :<|> apacH
  where
    usH :: Satisfies 'US RegionAuth -> Handler String
    usH _ = pure "us ok"

    euH :: Satisfies 'EU RegionAuth -> Handler String
    euH (Satisfies RegionProof auth) = pure (gdprExport auth) -- exact proof flows into gdprExport
    apacH :: Satisfies 'APAC RegionAuth -> Handler String
    apacH _ = pure "apac ok"

regionApp :: IO Application
regionApp = pure $ serveWithContext (Proxy @RegionAPI) (regionAuthHandler :. EmptyContext) regionServer

--------------------------------------------------------------------------------
-- Scheme 3: Permission sets

data Permission = PermRead | PermWrite | PermManage

$(deriveMemberRole ''Permission)

data PermAuth (ps :: [Permission]) = PermAuth

type instance AuthServerData (AuthProtect "perm-auth") = SomeRole PermAuth

permAuthHandler :: AuthHandler Request (SomeRole PermAuth)
permAuthHandler = mkAuthHandler $ \req ->
  case lookup "X-Perms" (requestHeaders req) of
    Just "reader" -> pure (somePermission [PermRead] PermAuth)
    Just "editor" -> pure (somePermission [PermRead, PermWrite] PermAuth)
    Just "manager" -> pure (somePermission [PermManage] PermAuth) -- deliberately not PermRead
    _ -> throwError err401

-- Demands the membership constraint (the generated HasPermWrite alias), not a
-- Proof value. Callable from any handler that can release Member 'PermWrite ps.
writeUser :: (HasPermWrite ps) => PermAuth ps -> IO ()
writeUser PermAuth = pure ()

type PermReadAPI = RequireRole "perm-auth" 'PermRead :> "read" :> Get '[JSON] String

type PermWriteAPI = RequireRole "perm-auth" 'PermWrite :> "write" :> Get '[JSON] String

type PermManageAPI = RequireRole "perm-auth" 'PermManage :> "manage" :> Get '[JSON] String

type PermReadWriteAPI = RequireRole "perm-auth" '[PermRead, PermWrite] :> "readwrite" :> Get '[JSON] String

type PermAPI = PermReadAPI :<|> PermWriteAPI :<|> PermManageAPI :<|> PermReadWriteAPI

permServer :: Server PermAPI
permServer = readH :<|> writeH :<|> manageH :<|> readWriteH
  where
    readH :: Satisfies 'PermRead PermAuth -> Handler String
    readH _ = pure "read ok"

    writeH :: Satisfies 'PermWrite PermAuth -> Handler String
    writeH (Satisfies proof auth) = liftIO (withMember proof (writeUser auth)) >> pure "write ok"

    manageH :: Satisfies 'PermManage PermAuth -> Handler String
    manageH _ = pure "manage ok"

    -- The subset proof releases BOTH memberships, so writeUser (which needs
    -- HasPermWrite) is callable with no re-check.
    readWriteH :: Satisfies '[PermRead, PermWrite] PermAuth -> Handler String
    readWriteH (Satisfies proof auth) =
      liftIO (withAllMembers proof (writeUser auth) >> pure "read+write ok")

permApp :: IO Application
permApp = pure $ serveWithContext (Proxy @PermAPI) (permAuthHandler :. EmptyContext) permServer

--------------------------------------------------------------------------------
-- Spec

hdr :: HeaderName -> ByteString -> [Header]
hdr name val = [(name, val), (hAccept, "application/json")]

roleReq :: ByteString -> ByteString -> WaiSession st SResponse
roleReq r path = request "GET" path (hdr "X-Role" r) ""

regionReq :: ByteString -> ByteString -> WaiSession st SResponse
regionReq r path = request "GET" path (hdr "X-Region" r) ""

perms :: ByteString -> ByteString -> WaiSession st SResponse
perms p path = request "GET" path (hdr "X-Perms" p) ""

spec :: Spec
spec = do
  describe "RequireRole" $ do
    -- Role x Route matrix (3 roles x 3 routes + unauthenticated = 12 cases)
    --
    --              | /viewer (Viewer) | /editor (Editor) | /admin (Admin)
    -- -------------|------------------|------------------|---------------
    -- Viewer       |       200        |       403        |      403
    -- Editor       |       200        |       200        |      403
    -- Admin        |       200        |       200        |      200
    -- No auth      |       401        |       401        |      401

    with roleApp $ do
      describe "hierarchical: /viewer (requires Viewer)" $ do
        it "Viewer -> 200" $ roleReq "viewer" "/viewer" `shouldRespondWith` 200
        it "Editor -> 200" $ roleReq "editor" "/viewer" `shouldRespondWith` 200
        it "Admin  -> 200" $ roleReq "admin" "/viewer" `shouldRespondWith` 200
        it "no auth -> 401" $ get "/viewer" `shouldRespondWith` 401

      describe "hierarchical: /editor (requires Editor)" $ do
        it "Viewer -> 403" $ roleReq "viewer" "/editor" `shouldRespondWith` 403
        it "Editor -> 200" $ roleReq "editor" "/editor" `shouldRespondWith` 200
        it "Admin  -> 200" $ roleReq "admin" "/editor" `shouldRespondWith` 200
        it "no auth -> 401" $ get "/editor" `shouldRespondWith` 401

      describe "hierarchical: /admin (requires Admin)" $ do
        it "Viewer -> 403" $ roleReq "viewer" "/admin" `shouldRespondWith` 403
        it "Editor -> 403" $ roleReq "editor" "/admin" `shouldRespondWith` 403
        it "Admin  -> 200, ban proof flows through" $
          roleReq "admin" "/admin" `shouldRespondWith` "\"banned by Sandy\"" {matchStatus = 200}
        it "no auth -> 401" $ get "/admin" `shouldRespondWith` 401

    with fallthroughApp $ do
      describe "same path, role-based fallthrough" $ do
        it "Admin  -> admin panel" $
          roleReq "admin" "/panel" `shouldRespondWith` "\"admin panel\"" {matchStatus = 200}
        it "Editor -> editor panel (falls through Admin)" $
          roleReq "editor" "/panel" `shouldRespondWith` "\"editor panel\"" {matchStatus = 200}
        it "Viewer -> viewer panel (falls through Admin, Editor)" $
          roleReq "viewer" "/panel" `shouldRespondWith` "\"viewer panel\"" {matchStatus = 200}
        it "no auth -> 401 (auth failure is fatal)" $ get "/panel" `shouldRespondWith` 401

    with anonApp $ do
      describe "public route behind RequireRole is unreachable" $ do
        it "no auth -> 401, not the public route" $ get "/panel" `shouldRespondWith` 401
        it "Viewer -> viewer panel (public route is dead code)" $
          roleReq "viewer" "/panel" `shouldRespondWith` "\"viewer panel\"" {matchStatus = 200}

    describe "auth handler invocation count" $ do
      it "Admin matches first alternative: auth runs 1 time" $ do
        counter <- newIORef 0
        app <- countingApp counter
        flip runWaiSession app $
          request "GET" "/panel" [("X-Role", "admin"), (hAccept, "application/json")] "" `shouldRespondWith` 200
        readIORef counter `shouldReturn` 1

      it "Editor falls through 1 alternative: auth runs 2 times" $ do
        counter <- newIORef 0
        app <- countingApp counter
        flip runWaiSession app $
          request "GET" "/panel" [("X-Role", "editor"), (hAccept, "application/json")] "" `shouldRespondWith` 200
        readIORef counter `shouldReturn` 2

      it "Viewer falls through 2 alternatives: auth runs 3 times" $ do
        counter <- newIORef 0
        app <- countingApp counter
        flip runWaiSession app $
          request "GET" "/panel" [("X-Role", "viewer"), (hAccept, "application/json")] "" `shouldRespondWith` 200
        readIORef counter `shouldReturn` 3

    -- Flat exact-match region matrix (equality, not hierarchy or membership)
    --          | /us | /eu | /apac
    -- us       | 200 | 403 | 403
    -- eu       | 403 | 200 | 403
    -- apac     | 403 | 403 | 200
    -- No auth  | 401 | 401 | 401
    with regionApp $ do
      describe "exact-match: US serves only /us" $ do
        it "/us    -> 200" $ regionReq "us" "/us" `shouldRespondWith` 200
        it "/eu    -> 403" $ regionReq "us" "/eu" `shouldRespondWith` 403
        it "/apac  -> 403" $ regionReq "us" "/apac" `shouldRespondWith` 403

      describe "exact-match: EU serves only /eu" $ do
        it "/eu    -> 200, GDPR proof flows through" $
          regionReq "eu" "/eu" `shouldRespondWith` "\"GDPR export for acme-eu\"" {matchStatus = 200}
        it "/us    -> 403" $ regionReq "eu" "/us" `shouldRespondWith` 403
        it "/apac  -> 403" $ regionReq "eu" "/apac" `shouldRespondWith` 403

      describe "exact-match: APAC serves only /apac" $ do
        it "/apac  -> 200" $ regionReq "apac" "/apac" `shouldRespondWith` 200
        it "/us    -> 403" $ regionReq "apac" "/us" `shouldRespondWith` 403

      it "no auth -> 401" $ get "/us" `shouldRespondWith` 401

    -- Non-hierarchical permission-set matrix (membership, not order).
    -- /readwrite requires a list '[PermRead, PermWrite]: needs BOTH (subset).
    --          | /read | /write | /manage | /readwrite
    -- reader   |  200  |  403   |  403    |    403
    -- editor   |  200  |  200   |  403    |    200
    -- manager  |  403  |  403   |  200    |    403
    -- No auth  |  401  |  401   |  401    |    401
    with permApp $ do
      describe "non-hierarchical: reader holds {PermRead}" $ do
        it "/read      -> 200" $ perms "reader" "/read" `shouldRespondWith` 200
        it "/write     -> 403" $ perms "reader" "/write" `shouldRespondWith` 403
        it "/manage    -> 403" $ perms "reader" "/manage" `shouldRespondWith` 403
        it "/readwrite -> 403 (holds PermRead but not PermWrite)" $
          perms "reader" "/readwrite" `shouldRespondWith` 403

      describe "non-hierarchical: editor holds {PermRead, PermWrite}" $ do
        it "/read      -> 200" $ perms "editor" "/read" `shouldRespondWith` 200
        it "/write     -> 200" $ perms "editor" "/write" `shouldRespondWith` 200
        it "/manage    -> 403" $ perms "editor" "/manage" `shouldRespondWith` 403
        it "/readwrite -> 200 (holds both PermRead and PermWrite)" $
          perms "editor" "/readwrite" `shouldRespondWith` "\"read+write ok\"" {matchStatus = 200}

      describe "non-hierarchical: manager holds {PermManage} only" $ do
        it "/manage    -> 200" $ perms "manager" "/manage" `shouldRespondWith` 200
        it "/read      -> 403 (PermManage does NOT imply PermRead)" $
          perms "manager" "/read" `shouldRespondWith` 403
        it "/write     -> 403" $ perms "manager" "/write" `shouldRespondWith` 403
        it "/readwrite -> 403 (holds neither PermRead nor PermWrite)" $
          perms "manager" "/readwrite" `shouldRespondWith` 403

      it "no auth -> 401" $ get "/read" `shouldRespondWith` 401
      it "no auth -> 401 (/readwrite)" $
        get "/readwrite" `shouldRespondWith` 401

    describe "developer experience: a role type with no deriver" $
      it "yields a guiding 'No Decidable instance' error" $ do
        result <- try (evaluate underivedDecidable) :: IO (Either SomeException ())
        case result of
          Left e -> show e `shouldContain` "No Decidable instance"
          Right () -> expectationFailure "expected the guiding error, but it type-checked"
